version: '3'
services:
  web:
    image: alexanderrybak/andersenhw4
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-DDB.PASSWORD=postgres -DDB.USERNAME=postgres -DDB.URL=jdbc:postgresql://db/andersen
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: andersen
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data: